services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vaultapi
      POSTGRES_USER: vaultapi
      POSTGRES_PASSWORD: vaultapi
    ports:
      - "5432:5432"
    volumes:
      - vaultapi_pgdata:/var/lib/postgresql/data

volumes:
  vaultapi_pgdata:
