// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VaultApi.Infrastructure.Persistence;

#nullable disable

namespace VaultApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902160422_AddContrato")]
    partial class AddContrato
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("RevendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("revenda_id");

                    b.HasKey("Id")
                        .HasName("pk_cliente");

                    b.HasIndex("RevendaId")
                        .HasDatabaseName("ix_cliente_revenda_id");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Contrato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_id");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<Guid?>("RevendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("revenda_id");

                    b.HasKey("Id")
                        .HasName("pk_contrato");

                    b.ToTable("contrato", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ContratoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<string>("TipoDesconto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_desconto");

                    b.Property<decimal?>("ValorAdesaoOverride")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_adesao_override");

                    b.Property<decimal?>("ValorDesconto")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_desconto");

                    b.Property<decimal?>("ValorMensalidadeOverride")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_mensalidade_override");

                    b.HasKey("Id")
                        .HasName("pk_contrato_item");

                    b.HasIndex("ContratoId")
                        .HasDatabaseName("ix_contrato_item_contrato_id");

                    b.ToTable("contrato_item", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ContratoItemModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<Guid>("ContratoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_item_id");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_id");

                    b.Property<Guid?>("ModuloVarianteId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_variante_id");

                    b.Property<decimal?>("ValorOverride")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_override");

                    b.HasKey("Id")
                        .HasName("pk_contrato_item_modulo");

                    b.HasIndex("ContratoItemId")
                        .HasDatabaseName("ix_contrato_item_modulo_contrato_item_id");

                    b.ToTable("contrato_item_modulo", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ContratoItemUnidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_item_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("TipoUnidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_unidade");

                    b.HasKey("Id")
                        .HasName("pk_contrato_item_unidade");

                    b.HasIndex("ContratoItemId", "TipoUnidade")
                        .IsUnique()
                        .HasDatabaseName("ix_contrato_item_unidade_contrato_item_id_tipo_unidade");

                    b.ToTable("contrato_item_unidade", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.HistoricoPrecoCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<string>("EntidadeTipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entidade_tipo");

                    b.Property<string>("TipoValor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_valor");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_anterior");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_novo");

                    b.HasKey("Id")
                        .HasName("pk_historico_preco_catalogo");

                    b.ToTable("historico_preco_catalogo", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<decimal?>("ValorAdesaoBase")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_adesao_base");

                    b.Property<decimal?>("ValorMensalidadeBase")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_mensalidade_base");

                    b.HasKey("Id")
                        .HasName("pk_modulo");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("ix_modulo_produto_id");

                    b.ToTable("modulo", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ModuloVariante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("modulo_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("TipoUnidadeAplicavel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_unidade_aplicavel");

                    b.Property<decimal>("ValorAdicionalPorUnidade")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_adicional_por_unidade");

                    b.HasKey("Id")
                        .HasName("pk_modulo_variante");

                    b.HasIndex("ModuloId")
                        .HasDatabaseName("ix_modulo_variante_modulo_id");

                    b.ToTable("modulo_variante", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_produto");

                    b.ToTable("produto", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ProdutoPrecoUnidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid")
                        .HasColumnName("produto_id");

                    b.Property<string>("TipoUnidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_unidade");

                    b.Property<decimal>("ValorAdesao")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_adesao");

                    b.Property<decimal>("ValorMensalidade")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_mensalidade");

                    b.HasKey("Id")
                        .HasName("pk_produto_preco_unidade");

                    b.HasIndex("ProdutoId", "TipoUnidade")
                        .IsUnique()
                        .HasDatabaseName("ix_produto_preco_unidade_produto_id_tipo_unidade");

                    b.ToTable("produto_preco_unidade", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Revenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_revenda");

                    b.ToTable("revenda", (string)null);
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<Guid?>("RevendaId")
                        .HasColumnType("uuid")
                        .HasColumnName("revenda_id");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("VaultApi.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.Revenda", null)
                        .WithMany()
                        .HasForeignKey("RevendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cliente_revenda_revenda_id");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ContratoItem", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.Contrato", null)
                        .WithMany("Itens")
                        .HasForeignKey("ContratoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contrato_item_contrato_contrato_id");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ContratoItemModulo", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.ContratoItem", null)
                        .WithMany("Modulos")
                        .HasForeignKey("ContratoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contrato_item_modulo_contrato_item_contrato_item_id");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ContratoItemUnidade", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.ContratoItem", null)
                        .WithMany("Unidades")
                        .HasForeignKey("ContratoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contrato_item_unidade_contrato_item_contrato_item_id");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.Produto", null)
                        .WithMany("Modulos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modulo_produto_produto_id");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ModuloVariante", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.Modulo", null)
                        .WithMany("Variantes")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_modulo_variante_modulo_modulo_id");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ProdutoPrecoUnidade", b =>
                {
                    b.HasOne("VaultApi.Domain.Entities.Produto", null)
                        .WithMany("PrecosPorUnidade")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_produto_preco_unidade_produto_produto_id");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Contrato", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.ContratoItem", b =>
                {
                    b.Navigation("Modulos");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("VaultApi.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Modulos");

                    b.Navigation("PrecosPorUnidade");
                });
#pragma warning restore 612, 618
        }
    }
}
